{% set name = "scmorph" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scmorph-{{ version }}.tar.gz
  sha256: a913568723642d5f37540c8c3b1869b53934ebda174b44f4d4ab3abd79094905

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - anndata >=0.8
    - certifi
    - formulaic
    - matplotlib-base >=3.6
    - numba >=0.56
    - numpy >=1.23
    - pandas >=1.5
    - patsy
    - pyarrow
    - pyod
    - scanpy
    - scikit-learn >=1.1
    - seaborn
    - session-info
    - tqdm

test:
  imports:
    - scmorph
  commands:
    - pip check
  requires:
    - pip
    - python >={{ python_min }}

about:
  summary: Single-cell morphological analysis
  home: https://github.com/jeskowagner/scmorph
  dev_url: https://github.com/jeskowagner/scmorph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeskowagner
