{% set name = "scmorph" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scmorph-{{ version }}.tar.gz
  sha256: 8f53f0a2c9d19c3c79e12b4cdfdfcc2a01e684ff3e2d5c9812036a6f32f25d82

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch-vcs
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - anndata >=0.8
    - certifi
    - formulaic
    - matplotlib-base >=3.6
    - numba >=0.56
    - numpy >=1.23
    - pandas >=1.5
    - patsy
    - pyarrow
    - pyod
    - scanpy
    - scikit-learn >=1.1
    - seaborn
    - session-info
    - tqdm

test:
  imports:
    - scmorph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Single-cell morphological analysis
  home: https://github.com/edbiomedai/scmorph
  dev_url: https://github.com/edbiomedai/scmorph
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeskowagner
