{% set name = "scmorph" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scmorph-{{ version }}.tar.gz
  sha256: a913568723642d5f37540c8c3b1869b53934ebda174b44f4d4ab3abd79094905

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - scanpy
    - anndata
    - pyarrow
    - pyod
    - tqdm
    - patsy
    - formulaic
    - numpy <1.23
    - pandas
    - scikit-learn
    - seaborn
    - matplotlib-base

test:
  imports:
    - scmorph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/scmorph/
  summary: Single-cell morphological analysis
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jeskowagner
